markdown: redcarpet
name: Open Opportunities Documentation
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: About
  url: index.html
  internal: true


repos:
- name: Open Opportunities
  description: Main repository
  url: https://github.com/18F/openopps-platform
- name: Open Opportunities Documentation
  description: Documentation repository
  url: https://github.com/18F/openopps-docs

back_link:
  url: "https://openopps.digitalgov.gov/"
  text: Back to Open Opportunities

google_analytics_ua: UA-48605964-17

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
